lines = [
"import plotly.express as px\n",
"import plotly.graph_objects as go\n",
"import pandas as pd\n",
"\n",
"COLORS = {\n",
'    "primary"    : "#4F46E5",\n',
'    "secondary"  : "#7C3AED",\n',
'    "success"    : "#10B981",\n',
'    "warning"    : "#F59E0B",\n',
'    "danger"     : "#EF4444",\n',
'    "background" : "#0F172A",\n',
'    "card"       : "#1E293B",\n',
'    "text"       : "#F1F5F9",\n',
'    "muted"      : "#94A3B8",\n',
"}\n",
"\n",
"CATEGORY_COLORS = {\n",
'    "Electronics"    : "#4F46E5",\n',
'    "Clothing"       : "#7C3AED",\n',
'    "Home & Kitchen" : "#10B981",\n',
'    "Sports"         : "#F59E0B",\n',
'    "Books"          : "#EF4444",\n',
"}\n",
"\n",
"REGION_COLORS = {\n",
'    "North"   : "#4F46E5",\n',
'    "South"   : "#10B981",\n',
'    "East"    : "#F59E0B",\n',
'    "West"    : "#EF4444",\n',
'    "Unknown" : "#94A3B8",\n',
"}\n",
"\n",
"LAYOUT_BASE = dict(\n",
'    paper_bgcolor = COLORS["background"],\n',
'    plot_bgcolor  = COLORS["background"],\n',
'    font          = dict(color=COLORS["text"], family="Inter, sans-serif"),\n',
"    margin        = dict(l=40, r=40, t=60, b=40),\n",
'    legend        = dict(bgcolor="rgba(0,0,0,0)", font=dict(color=COLORS["text"])),\n',
")\n",
"\n",
"\n",
"def chart_monthly_trend(df):\n",
'    trend = df.groupby("year_month")["revenue"].sum().reset_index().sort_values("year_month")\n',
"    fig = go.Figure()\n",
"    fig.add_trace(go.Scatter(\n",
'        x=trend["year_month"], y=trend["revenue"],\n',
'        mode="lines+markers", name="Monthly Revenue",\n',
'        line=dict(color=COLORS["primary"], width=3),\n',
'        marker=dict(size=6, color=COLORS["primary"]),\n',
'        fill="tozeroy", fillcolor="rgba(79, 70, 229, 0.15)",\n',
'        hovertemplate="<b>%{x}</b><br>Revenue: $%{y:,.2f}<extra></extra>",\n',
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="📈 Monthly Revenue Trend", font=dict(size=18)),\n',
'        xaxis=dict(title="Month", showgrid=False, color=COLORS["muted"]),\n',
'        yaxis=dict(title="Revenue ($)", showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_revenue_by_category(df):\n",
'    cat = df.groupby("category")["revenue"].sum().reset_index().sort_values("revenue", ascending=True)\n',
"    fig = go.Figure(go.Bar(\n",
'        x=cat["revenue"], y=cat["category"], orientation="h",\n',
'        marker_color=[CATEGORY_COLORS.get(c, COLORS["primary"]) for c in cat["category"]],\n',
'        hovertemplate="<b>%{y}</b><br>Revenue: $%{x:,.2f}<extra></extra>",\n',
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="🏆 Revenue by Category", font=dict(size=18)),\n',
'        xaxis=dict(title="Revenue ($)", showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
'        yaxis=dict(title="", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_revenue_by_region(df):\n",
'    reg = df.groupby("region")["revenue"].sum().reset_index()\n',
"    fig = go.Figure(go.Pie(\n",
'        labels=reg["region"], values=reg["revenue"], hole=0.55,\n',
'        marker=dict(colors=[REGION_COLORS.get(r, COLORS["primary"]) for r in reg["region"]]),\n',
'        hovertemplate="<b>%{label}</b><br>Revenue: $%{value:,.2f}<br>Share: %{percent}<extra></extra>",\n',
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="🌍 Revenue by Region", font=dict(size=18)),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_yoy_comparison(df):\n",
'    monthly = df.groupby(["year", "month_name", "month"])["revenue"].sum().reset_index().sort_values("month")\n',
"    fig = go.Figure()\n",
'    for year, color in [(2023, COLORS["primary"]), (2024, COLORS["success"])]:\n',
'        data = monthly[monthly["year"] == year]\n',
"        fig.add_trace(go.Bar(\n",
'            x=data["month_name"], y=data["revenue"],\n',
'            name=str(year), marker_color=color,\n',
'            hovertemplate=f"<b>%{{x}} {year}</b><br>Revenue: $%{{y:,.2f}}<extra></extra>",\n',
"        ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="📊 2023 vs 2024 Monthly Revenue", font=dict(size=18)),\n',
'        barmode="group",\n',
'        xaxis=dict(title="Month", color=COLORS["muted"]),\n',
'        yaxis=dict(title="Revenue ($)", showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_top_products(df):\n",
'    prod = df.groupby("product")["revenue"].sum().reset_index().sort_values("revenue", ascending=False).head(10).sort_values("revenue", ascending=True)\n',
"    fig = go.Figure(go.Bar(\n",
'        x=prod["revenue"], y=prod["product"], orientation="h",\n',
'        marker_color=COLORS["secondary"],\n',
'        hovertemplate="<b>%{y}</b><br>Revenue: $%{x:,.2f}<extra></extra>",\n',
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="🥇 Top 10 Products by Revenue", font=dict(size=18)),\n',
'        xaxis=dict(title="Revenue ($)", showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
'        yaxis=dict(color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_discount_impact(df):\n",
"    fig = px.scatter(\n",
'        df, x="discount", y="revenue", color="category",\n',
'        size="quantity", hover_data=["product", "region"],\n',
"        color_discrete_map=CATEGORY_COLORS,\n",
'        labels={"discount": "Discount Rate", "revenue": "Revenue ($)"},\n',
"    )\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="🔍 Discount Impact on Revenue", font=dict(size=18)),\n',
'        xaxis=dict(tickformat=".0%", color=COLORS["muted"]),\n',
'        yaxis=dict(showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_forecast(df):\n",
'    daily = df.groupby("order_date")["revenue"].sum().reset_index().sort_values("order_date")\n',
'    daily["moving_avg"] = daily["revenue"].rolling(window=30, min_periods=1).mean()\n',
"    fig = go.Figure()\n",
"    fig.add_trace(go.Scatter(\n",
'        x=daily["order_date"], y=daily["revenue"],\n',
'        mode="lines", name="Daily Revenue",\n',
'        line=dict(color="rgba(79,70,229,0.25)", width=1),\n',
'        hovertemplate="<b>%{x}</b><br>Daily: $%{y:,.2f}<extra></extra>",\n',
"    ))\n",
"    fig.add_trace(go.Scatter(\n",
'        x=daily["order_date"], y=daily["moving_avg"],\n',
'        mode="lines", name="30-Day Moving Avg",\n',
'        line=dict(color=COLORS["success"], width=3),\n',
'        hovertemplate="<b>%{x}</b><br>30D Avg: $%{y:,.2f}<extra></extra>",\n',
"    ))\n",
"    fig.add_trace(go.Scatter(\n",
'        x=daily["order_date"], y=daily["moving_avg"],\n',
'        fill="tozeroy", fillcolor="rgba(16,185,129,0.08)",\n',
'        line=dict(color="rgba(0,0,0,0)"),\n',
"        showlegend=False, hoverinfo='skip',\n",
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="📉 Revenue Trend & 30-Day Moving Average", font=dict(size=18)),\n',
'        xaxis=dict(title="Date", showgrid=False, color=COLORS["muted"]),\n',
'        yaxis=dict(title="Revenue ($)", showgrid=True, gridcolor="rgba(148,163,184,0.1)", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
"\n",
"\n",
"def chart_heatmap(df):\n",
"    df = df.copy()\n",
'    df["day_of_week"] = df["order_date"].dt.day_name()\n',
'    df["month_name"]  = df["order_date"].dt.strftime("%b")\n',
'    df["month_num"]   = df["order_date"].dt.month\n',
'    pivot = df.groupby(["day_of_week", "month_name", "month_num"])["revenue"].sum().reset_index()\n',
'    day_order   = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]\n',
'    month_order = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]\n',
'    pivot  = pivot[pivot["day_of_week"].isin(day_order)]\n',
"    matrix = pivot.pivot_table(\n",
'        index="day_of_week", columns="month_name", values="revenue", aggfunc="sum",\n',
"    ).reindex(index=day_order, columns=month_order).fillna(0)\n",
"    fig = go.Figure(go.Heatmap(\n",
"        z=matrix.values,\n",
"        x=matrix.columns.tolist(),\n",
"        y=matrix.index.tolist(),\n",
"        colorscale=[\n",
'            [0.0,  "#0F172A"],\n',
'            [0.25, "#1E3A5F"],\n',
'            [0.5,  "#1D4ED8"],\n',
'            [0.75, "#4F46E5"],\n',
'            [1.0,  "#A78BFA"],\n',
"        ],\n",
'        hovertemplate="<b>%{y} — %{x}</b><br>Revenue: $%{z:,.0f}<extra></extra>",\n',
"        showscale=True,\n",
'        colorbar=dict(title="Revenue", titlefont=dict(color=COLORS["muted"]), tickfont=dict(color=COLORS["muted"]), tickprefix="$"),\n',
"    ))\n",
"    fig.update_layout(\n",
"        **LAYOUT_BASE,\n",
'        title=dict(text="🗓️ Revenue Heatmap — Day of Week vs Month", font=dict(size=18)),\n',
'        xaxis=dict(title="Month", color=COLORS["muted"], side="bottom"),\n',
'        yaxis=dict(title="Day of Week", color=COLORS["muted"]),\n',
"    )\n",
"    return fig\n",
]

with open('src/charts.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print("src/charts.py written successfully!")